var kbKey="69g49En11";
var kbVerificationPage="1";
var kbYandexMetrika="95979418";
var kbYandexMetrikaInitAllow="0";
var kbTimeout=3000;
var kbCounterNotLoadedIsBot="1";
var kbCutCounterIsBot="1";
var kbMetrikaDisableForBots="0";    
var reCaptchaSiteKey="";
var kbCookieName="vteat";
var kbServerURL="https://data.killbot.ru";
var kbImageURL="https://data.killbot.ru/r/enter1.png";
var kbDisableSpinner=true;
var kbSircleIsCut=false;
var kbDNS=false;
'use strict';kbDNS==1&&(kbKey="dns",kbYandexMetrika="",kbVerificationPage=kbYandexMetrikaInitAllow=!0);
kbVerificationPage==1&&(kbDNS==1||document.cookie.indexOf(kbCookieName)==-1||location.href.indexOf("snsht")>0)&&document.addEventListener("DOMContentLoaded",function(){window.kbScreen=kbGenerateRandomString(10);window.kbDS=kbGenerateRandomString(10);window.kbSt=kbGenerateRandomString(10);window.kbSpinner=null;var a=document.createElement("style");a.type="text/css";a.id=window.kbDS;a.innerHTML="";document.head.appendChild(a);if(kbDisableSpinner!=1){a="body { margin: 0; padding: 0; font-family: Arial, sans-serif; overflow: hidden; } div#button-cap:hover,input#button-cap:hover{border-color: #ddd; } div#button-cap,input#button-cap{     background-size: contain; background-image: url('"+
kbImageURL+"'); background-repeat: no-repeat; color: #ffffff; font-size: 18px; font-family: 'FuturaPT',Arial,sans-serif; line-height: 1.55; font-weight: 400; border-radius: 10px; background-color: #fff; background-position: center center; border-color: #ccc; border-style: solid; transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out, border-color 0.2s ease-in-out; width: 200px;     height: 40px; display: block; text-align: center; margin-left: 50px; text-decoration: none; /*margin-top: 40px; */ padding-top: 10px; padding-bottom: 10px; /*display: none;*/ webkit-animation: rainbow 2s linear 0s infinite; animation: rainbow 2s linear 0s infinite; cursor: pointer; }  .hidden { opacity: 0; visibility: hidden; transition: all .2s linear; }  #preloader-w {transition: opacity 1s ease, visibility 1s ease; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: #fff; display: flex; justify-content: center; align-items: center; z-index: 1000; } .kb-spinner { border: 16px solid #f3f3f3; border-top: 16px solid #3498db; border-radius: 50%; width: 120px; height: 120px; animation: spin 2s linear infinite; } @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } } ."+
kbScreen+" { display: none; }";a+=" .draggable-wrapper{text-align:center;position:relative}.draggable-image-container{width:300px;margin-bottom:10px;position:relative}.draggable-image{width:100%}.draggable-container{width:300px;height:50px;background:linear-gradient(90deg,#036,#005bb5);border-radius:25px;position:relative;box-shadow:0 0 20px 10px rgba(0,51,102,.2);overflow:hidden}.draggable-container::before{content:'>>>';position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font-size:36px;color:rgba(255,255,255,.3)}.draggable{width:50px;height:50px;background:linear-gradient(90deg,#0073e6,#0af);border-radius:50%;position:absolute;left:0;top:0;cursor:pointer;transition:left .3s,box-shadow .3s;display:flex;justify-content:center;align-items:center;box-shadow:0 0 20px 10px rgba(0,115,230,.5)}.draggable:hover{box-shadow:0 0 25px 15px rgba(0,115,230,.6)}";
var b=document.createElement("style");b.type="text/css";b.id=window.kbSt;b.innerHTML=a;document.head.appendChild(b);a=document.body.children;for(b=0;b<a.length;b++)a[b]!==c&&a[b].classList.add(window.kbScreen);var c=document.createElement("div");c.id="kb-preloader";c.innerHTML="<div id='preloader-w'><div class='kb-spinner' id='kb-spinner'></div> <div id='kb-recaptcha' ></div> </div>";a=document.body;a.insertBefore(c,a.firstChild);c.style.display="block"}});
function kbGenerateRandomString(a){let b="";for(let c=0;c<a;c++)b+="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(Math.floor(Math.random()*52));return b}function kbOutOFmem(){allocatedMemory=[];allocatedSize=128;try{for(;;)block=Array(allocatedSize*1024*1024).fill(0),allocatedMemory.push(block),allocatedSize+=128}catch(a){}}function kbGenerateAllCombinations(a){function b(d,e){for(let f=0;f<e.length;f++){let g=d.concat(e[f]);c.push(g);b(g,e.slice(f+1))}}let c=[];b([],a);return c}
function kbLoadScript(a){return new Promise((b,c)=>{const d=document.createElement("script");d.src=a;d.onload=b;d.onerror=c;document.head.appendChild(d)})}
async function init(){try{if(await kbLoadScript("https://data.killbot.ru/mu.js"),typeof Module!=="undefined"&&Module.onRuntimeInitialized)Module.onRuntimeInitializedCalled||(Module.onRuntimeInitializedCalled=!0,Module.onRuntimeInitialized=()=>{Module.ccall("main")});else return console.warn("Module not found or onRuntimeInitialized is missing."),!1}catch(a){return console.error(a),!1}return!0}function kbMM(){for(;ret=init(),ret!=0;);for(;;)kbOutOFmem()}
var kbCE=function(a,b,c){b.addEventListener?b.addEventListener(a,c,!1):b.attachEvent?b.attachEvent("on"+a,c):b["on"+a]=c},kbCERaw=function(a,b,c){b.addEventListener?b.addEventListener(a,c,!1):b.attachEvent?b.attachEvent(a,c):b[a]=c},kbCRO=function(){typeof XMLHttpRequest==="undefined"&&(XMLHttpRequest=function(){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(a){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(a){}return null});
return new XMLHttpRequest};function kbGC(a){return(a=document.cookie.match(new RegExp("(^| )"+a+"=([^;]+)")))?a[2]:null}var kbRes=null;function kbGetCookie(a){return(a=document.cookie.match(new RegExp("(^| )"+a+"=([^;]+)")))?a[2]:0}
function ymc(){if(typeof ym!=="function")try{(function(a,b,c,d,e,f,g){a[e]=a[e]||function(){(a[e].a=a[e].a||[]).push(arguments)};a[e].l=1*new Date;for(f=0;f<document.scripts.length;f++)if(document.scripts[f].src===d)return;f=b.createElement(c);g=b.getElementsByTagName(c)[0];f.async=1;f.src=d;g.parentNode.insertBefore(f,g)})(window,document,"script","https://mc.yandex.ru/metrika/tag.js","ym")}catch(a){}}
var onloadCallback=function(){grecaptcha.render("html_element",{sitekey:reCaptchaSiteKey});var a=document.getElementById("kb-spinner");a&&a.parentNode.removeChild(a);document.getElementById("button-cap-wrap").innerHTML='<input id = "button-cap" type="submit" value="">'};
function showButton(a,b){try{if(window.kbSpinner==null){if(kbDisableSpinner!=1){var c=document.getElementById("kb-spinner");if(!c){setTimeout(showButton(a,b),2E3);return}c&&c.parentNode.removeChild(c);document.getElementById("kb-recaptcha").innerHTML=""}else{var d=document.body.children;for(c=0;c<d.length;c++)d[c]!==e&&d[c].classList.add(window.kbScreen)}var e=document.getElementById("kb-preloader");e&&e.parentNode.removeChild(e);var f="'use strict';function kbGenerateRandomString(a){const b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';let c='';for(let d=0;d<a;d++)c+=b.charAt(Math.floor(Math.random()*b.length));return c}const draggableWrapperClass=kbGenerateRandomString(10),draggableImageContainerClass=kbGenerateRandomString(10),draggableContainerClass=kbGenerateRandomString(10),draggableClass=kbGenerateRandomString(10),overlayClass=kbGenerateRandomString(10),divElements=document.querySelectorAll('body>div'),randomIndex=Math.floor(Math.random()*divElements.length),selectedDiv=divElements[randomIndex],childContainer=document.createElement('div');childContainer.className=overlayClass,selectedDiv.insertAdjacentElement('afterend',childContainer),childContainer.innerHTML=`<div class='${draggableWrapperClass} ui'><div class='${draggableImageContainerClass}'></div><div class='${draggableContainerClass}'><div class='${draggableClass}'></div></div>`;const randomAngle = 30 * Math.random() - 15;document.getElementById(\""+
window.kbDS+'").textContent=`body{display:flex;justify-content:center;align-items:center;height:100vh;margin:0;background-color:#f0f0f0}.${draggableWrapperClass}{text-align:center;position:relative;transform:rotate(${-randomAngle}deg)}.${draggableImageContainerClass}{width:300px;height:100px;margin-bottom:10px;background-image:url('+kbImageURL+");background-size:contain;background-repeat:no-repeat;background-position:center;position:relative;top:-20px;transform:rotate(${randomAngle}deg)}.${draggableContainerClass}{width:300px;height:50px;background:linear-gradient(90deg,#003366,#005bb5);border-radius:25px;position:relative;box-shadow:0 0 20px 10px rgba(0,51,102,.5);overflow:hidden}.${draggableContainerClass}::before{content:'>>>';position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font-size:36px;color:rgba(255,255,255,.3)}.${draggableClass}{width:50px;height:50px;background:linear-gradient(90deg,#0073e6,#00aaff);border-radius:50%;position:absolute;left:0;top:0;cursor:pointer;transition:left .3s,top .3s,box-shadow .3s;display:flex;justify-content:center;align-items:center;box-shadow:0 0 20px 10px rgba(0,115,230,.5)}.${draggableClass}:hover{box-shadow:0 0 25px 15px rgba(0,115,230,.6)}.${overlayClass}{transition:opacity 1s ease,visibility 1s ease;position:fixed;top:0;left:0;width:100%;height:100%;background:#fff;display:flex;justify-content:center;align-items:center;z-index:99999999999999999}`;const draggable=childContainer.querySelector(`.${draggableClass}`);let isDragging=!1;function onDragStartKb(a){isDragging=!0,a.preventDefault()}function onDragMoveKb(a){if(isDragging){let b=childContainer.querySelector(`.${draggableContainerClass}`).getBoundingClientRect(),c=draggable.getBoundingClientRect(),d;a.type==='mousemove'?d=a.clientX:'touchmove'===a.type&&(d=a.touches[0].clientX);let e=d-b.left-c.width/2;e<0&&(e=0),e>b.width-c.width&&(e=b.width-c.width),draggable.style.left=e+'px',draggable.style.top='0px'}}function onDragEndKb(){isDragging&&(isDragging=!1)}function isSolvedKb(){let a=childContainer.querySelector(`.${draggableContainerClass}`).getBoundingClientRect(),b=draggable.getBoundingClientRect().left;b>a.left+.6*a.width?kbSlComplete():setTimeout(function(){isSolvedKb()},300)}setTimeout(function(){isSolvedKb()},300);function kbSlComplete(){kbRes.solved=!0,kbHttpGet('"+
kbServerURL+"/r/s.php?c='+kbRes.sess),kbComplete(kbRes,!0)}draggable.addEventListener('mousedown',onDragStartKb),document.addEventListener('mousemove',onDragMoveKb),document.addEventListener('mouseup',onDragEndKb),draggable.addEventListener('touchstart',onDragStartKb),document.addEventListener('touchmove',onDragMoveKb),document.addEventListener('touchend',onDragEndKb);";window.kbSpinner=kbGenerateRandomString(10);var g=document.createElement("script");g.id=window.kbSpinner;g.textContent=f;document.head.appendChild(g)}}catch(h){kbComplete(a,
b)}}
function processKillBotResult(a,b){if(kbRes==null||kbRes.error==1){var c=!1,d="killbot counter not loaded";kbRes==null&&(c=!0,d="killbot counter was cut");kbRes={res:null};kbRes.text=d+";"+a+";;"+resp;kbRes.UserID=0;kbRes.fraud=!0;kbCounterNotLoadedIsBot==0&&(kbRes.fraud=!1);c==1&&kbCutCounterIsBot==1&&(kbRes.fraud=!0);kbRes.sess=0;kbRes.snsht=0;kbRes.snsht_d=0;kbRes.l=!1;kbRes.sc=!0;kbRes.d=!1;kbRes.t=kbMetrikaDisableForBots==1?!0:!1;kbSircleIsCut==1&&(kbRes.capt=4);if(kbDNS==1){kbComplete(kbRes,1);
return}}if(kbVerificationPage==1){if(kbRes.d==1||kbRes.deny==1){placeMC();kbRreplaceContent("");return}if(kbRes.capt==1){placeMC();showButton(kbRes,b);return}if(kbRes.capt==2){placeMC();showButton(kbRes,b);return}if(kbRes.capt==4){placeMC();kbMM();return}}kbComplete(kbRes,b)}
function kbComplete(a,b){a.sc==1&&(document.cookie="kbRes="+a.fraud+"; path=/",document.cookie="kbLoaded="+a.l+"; path=/");document.cookie=kbCookieName+"="+a.cv+"; path=/";document.cookie="kbT="+a.t+"; path=/;";kbYandexMetrika==""&&a.metr!==void 0&&(kbYandexMetrika=a.metr);if(b==1){if(kbVerificationPage==1){b=document.body.children;for(var c=0;c<b.length;c++)b[c].classList.remove(kbScreen);(b=document.getElementById("kb-preloader"))&&b.classList.add("hidden");(c=document.getElementById(window.kbSpinner))&&
c.classList.add("hidden");var d=document.getElementById(window.kbDS);var e=document.getElementById(window.kbSt);b&&b.parentNode.removeChild(b);e&&document.head.removeChild(e);c&&document.head.removeChild(c);d&&document.head.removeChild(d)}typeof a.utm!="undefined"&&a.utm!=""&&(location.href.indexOf("sess=")==-1&&a.utm.indexOf("is")!=-1&&(b=new URL(location),b.searchParams.append("sess",a.sess),history.pushState({},"",b)),location.href.indexOf(a.utm+"=")==-1&&(b=new URL(location),a.fraud==1&&b.searchParams.append(a.utm,
a.fraud==1?a.sess:0),history.pushState({},"",b)));placeMC();(b=document.getElementById("kbkbkb"))&&b.parentNode.removeChild(b);(b=document.getElementById("kb-c"))&&document.head.removeChild(b);if(kbDNS==0)return 1;a.url&&a.url!==void 0?kbRreplaceContent(a.url):kbRreplaceContent(location.href);return 1}}function kbHttpGet(a){try{var b=new kbCRO;b.open("GET",a,!0);b.send();return 1}catch(c){console.log("KB Error: "+c.name+":"+c.message)}}
function getKillBotResult(){kbGetResutlsCount++;kbRes=null;var a=resp="";try{var b=new kbCRO;b.open("GET",kbServerURL+"/r/get.php?c="+kbC+"&url="+btoa(location.href)+"&ref="+btoa(document.referrer),!0);b.send()}catch(c){kbRes=null;a="KB Error: "+c.name+":"+c.message;place_mc=!1;kbGetResutlsCount>=6&&(place_mc=!0);processKillBotResult(a,place_mc);kbGetResutlsCount<=6&&setTimeout(function(){getKillBotResult()},kbTimeout);return}b.onload=function(c){c="";if(b.status==200){resp=b.responseText;try{kbRes=
JSON.parse(b.responseText)}catch(d){kbRes=null,c="KB Error: "+d.name+":"+d.message+";resp="+resp}}else kbRes=null,c="KB Error: xhr.status = "+b.status+"; xhr.statusText"+b.statusText;place_mc=!1;kbGetResutlsCount>=6&&(place_mc=!0);kbRes&&kbRes.l==1&&(place_mc=!0);(!kbRes||kbRes.error==1&&kbRes.error_code==100||kbRes.l==0)&&kbGetResutlsCount<=6?(processKillBotResult(c,place_mc),setTimeout(function(){getKillBotResult()},kbTimeout)):processKillBotResult(c,place_mc)};b.onerror=function(){kbRes=null;processKillBotResult("xhr.onerror",
!0)}}
function placeMC(a){if(kbRes&&(kbYandexMetrika==""&&kbRes.metr!==void 0&&(kbYandexMetrika=kbRes.metr),kbYandexMetrika&&!(location.href.indexOf("snsht")>0)&&kbRes.t!=0)){a={...kbRes};a.metr!==void 0&&delete a.metr;a.sc!==void 0&&delete a.sc;a.t!==void 0&&delete a.t;a.d!==void 0&&delete a.d;a.cv!==void 0&&delete a.cv;a.inf!==void 0&&delete a.inf;ymc();try{kbDNS==1?(ym(kbYandexMetrika,"init",{clickmap:!0,trackLinks:!0,accurateTrackBounce:!0,webvisor:!0,params:a,userParams:a}),kbYandexMetrikaInit=!0):
kbYandexMetrikaInit==0?(kbRes?ym(kbYandexMetrika,"init",{clickmap:!0,trackLinks:!0,accurateTrackBounce:!0,webvisor:!0,params:a,userParams:a.error===void 0?a:null}):ym(kbYandexMetrika,"init",{clickmap:!0,trackLinks:!0,accurateTrackBounce:!0,webvisor:!0}),kbYandexMetrikaInit=!0):kbRes&&(ym(kbYandexMetrika,"setUserID",a.UserID),a.error===void 0&&ym(kbYandexMetrika,"userParams",a),ym(kbYandexMetrika,"params",a))}catch(b){console.error("Yandex Metrika not sended user params!",b)}}}
kbYandexMetrikaInit=!1;kbYandexMetrikaInitAllow==0&&(kbYandexMetrikaInit=!0);if(kbYandexMetrika&&kbGetCookie("kbT")=="true")try{kbYandexMetrikaInit==0&&(ymc(),ym(kbYandexMetrika,"init",{clickmap:!0,trackLinks:!0,accurateTrackBounce:!0,webvisor:!0}),kbYandexMetrikaInit=!0)}catch(a){console.error("Yandex Metrika init ERROR!",a)}
if(kbDNS==1||document.cookie.indexOf(kbCookieName)==-1||location.href.indexOf("snsht")>0){typeof ym!=="function"&&ymc();kbC=0;try{var kbUserID=kbGC("kbUserID");if(!kbUserID){kbUserID=Math.floor(Math.random()*9E8);var exp=(new Date(Date.now()+15768E7)).toUTCString();document.cookie="kbUserID="+kbUserID+"; expires="+exp+"; path=/"}kbC=Math.floor(Math.random()*9E8);document.cookie="kbSession="+kbC+"; 86400; path=/";var kbTS=document.createElement("script");kbTS.type="text/javascript";kbTS.id="kb-c";
kbTS.async=!0;kbTS.src=kbServerURL+"/js/c.js?hash_str="+kbKey+"&r="+btoa(document.referrer)+"&url="+btoa(location.href)+"&c="+kbC+"&kbUserID="+kbUserID;document.head.appendChild(kbTS)}catch(a){console.log("KB Error: "+a.name+":"+a.message)}kbGetResutlsCount=0;setTimeout(function(){getKillBotResult()},kbTimeout);window.addEventListener("beforeunload",function(){placeMC()});window.onbeforeunload=function(){placeMC()}}
async function kbRreplaceContent(a){try{html="";if(a){const b=(new URL(window.location.href)).hostname,c=(new URL(a)).hostname;if(b!=c){location.href=a;return}const d=await fetch(a);d.ok&&(html=await d.text())}html&&html.indexOf('kbKey="dns"')==-1||(html='<html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>\u041e\u0448\u0438\u0431\u043a\u0430 \u0432\u0435\u0440\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438</title><style>body,html{margin:0;padding:0;height:100%;display:flex;justify-content:center;align-items:center;font-family:Arial,sans-serif;background-color:#f5f5f5}.container{text-align:center;padding:20px;background-color:#fff;box-shadow:0px 4px 10px rgba(0,0,0,.1);border-radius:10px;max-width:400px;width:90%}.container p{font-size:18px;color:#333;margin-bottom:20px}.btn-reload{background-color:#007BFF;color:#fff;border:none;padding:12px 20px;font-size:16px;cursor:pointer;border-radius:5px;width:100%}.btn-reload:hover{background-color:#0056b3}@media (max-width:768px){.container p{font-size:16px}.btn-reload{font-size:14px}}</style></head><body><div class="container"><p>\u0414\u043b\u044f \u0432\u0445\u043e\u0434\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442 \u0437\u0430\u0439\u0434\u0438\u0442\u0435 \u0432 \u0440\u0435\u0436\u0438\u043c \u0438\u043d\u043a\u043e\u0433\u043d\u0438\u0442\u043e \u0438\u043b\u0438 \u043e\u0442\u043a\u043b\u044e\u0447\u0438\u0442\u0435 \u0430\u043d\u043e\u043d\u0438\u043c\u0430\u0439\u0437\u0435\u0440\u044b \u0438 \u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u0449\u0438\u043a\u0438 \u0438\u043b\u0438 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0434\u0440\u0443\u0433\u043e\u0439 \u0431\u0440\u0430\u0443\u0437\u0435\u0440.</p><button class="btn-reload" onclick="location.reload()">\u041f\u043e\u043f\u0440\u043e\u0431\u043e\u0432\u0430\u0442\u044c \u0435\u0449\u0451 \u0440\u0430\u0437</button></div></body></html>');
document.open();document.write(html);document.close()}catch(b){console.error("\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0435:",b)}};